//
// Created by dingjing on 2/19/25.
//

#ifndef html_parser_INSERTION_MODE_H
#define html_parser_INSERTION_MODE_H
#include "macros/macros.h"

C_BEGIN_EXTERN_C

typedef enum
{
    GUMBO_INSERTION_MODE_INITIAL,
    GUMBO_INSERTION_MODE_BEFORE_HTML,
    GUMBO_INSERTION_MODE_BEFORE_HEAD,
    GUMBO_INSERTION_MODE_IN_HEAD,
    GUMBO_INSERTION_MODE_IN_HEAD_NOSCRIPT,
    GUMBO_INSERTION_MODE_AFTER_HEAD,
    GUMBO_INSERTION_MODE_IN_BODY,
    GUMBO_INSERTION_MODE_TEXT,
    GUMBO_INSERTION_MODE_IN_TABLE,
    GUMBO_INSERTION_MODE_IN_TABLE_TEXT,
    GUMBO_INSERTION_MODE_IN_CAPTION,
    GUMBO_INSERTION_MODE_IN_COLUMN_GROUP,
    GUMBO_INSERTION_MODE_IN_TABLE_BODY,
    GUMBO_INSERTION_MODE_IN_ROW,
    GUMBO_INSERTION_MODE_IN_CELL,
    GUMBO_INSERTION_MODE_IN_SELECT,
    GUMBO_INSERTION_MODE_IN_SELECT_IN_TABLE,
    GUMBO_INSERTION_MODE_IN_TEMPLATE,
    GUMBO_INSERTION_MODE_AFTER_BODY,
    GUMBO_INSERTION_MODE_IN_FRAMESET,
    GUMBO_INSERTION_MODE_AFTER_FRAMESET,
    GUMBO_INSERTION_MODE_AFTER_AFTER_BODY,
    GUMBO_INSERTION_MODE_AFTER_AFTER_FRAMESET
} GumboInsertionMode;

C_END_EXTERN_C

#endif // html-parser_INSERTION_MODE_H
